title: " "
theme: minima
github_username: leg-ifgoiano
markdown: kramdown
tagline: " "
description: " "
tags:
  - GitHub
  - GitHub Pages
social-network-links:
  github: jekyll
navbar:
  right:
    - text: GitHub
      icon: fa-github fa-lg
