title: "PTTs CRENAC"
theme: minima
github_username: leg-ifgoiano
markdown: kramdown
description: " "
social_icons:
    enable: true
    icons_only: true
    transition: true
social:
    GitHub: https://github.com/ppgcrenacurt|| github
    E-Mail: mailto:ppgcrenac.urt@ifgoiano.edu.br || envelope
